In [1]:
pip install numpy


In [5]:
import numpy as np

# Матрица игры (замените на свою)
matrix_data = [
    [4, 0, 3, 8, 11],
    [6, 9, 1, 4, 3],
    [2, 3, 4, 3, 7],
    [2, 11, 5, 0, 4],
    [11, 5, 7, 3, 1]
]

# Смешанная стратегия P для Игрока A
P = [0.4, 0.1, 0.0, 0.01, 0.4]

# Смешанная стратегия Q для Игрока B
Q = [0.2, 0.2, 0.2, 0.4, 0.0]


# 2. ПРЕОБРАЗОВАНИЕ ДАННЫХ
# Преобразуем списки в массивы numpy для удобных вычислений
matrix = np.array(matrix_data)
p_vec = np.array(P)
q_vec = np.array(Q)

print(f"Дано:\nПлатежная матрица:\n{matrix}\n")
print(f"Смешанная стратегия P (Игрок А): {p_vec}")
print(f"Смешанная стратегия Q (Игрок B): {q_vec}\n")


# 3. ПОИСК СЕДЛОВОЙ ТОЧКИ (РЕШЕНИЕ В ЧИСТЫХ СТРАТЕГИЯХ)

print("--- 1. Поиск седловой точки ---")

# Нижняя цена игры (альфа) - максимум из минимумов строк
# axis=1 означает "по строкам"
lower_price = matrix.min(axis=1).max()

# Верхняя цена игры (бета) - минимум из максимумов столбцов
# axis=0 означает "по столбцам"
upper_price = matrix.max(axis=0).min()

print(f"Нижняя цена игры (α) = {lower_price}")
print(f"Верхняя цена игры (β) = {upper_price}")

if lower_price == upper_price:
    print(f"Седловая точка ЕСТЬ. v = {lower_price}")
else:
    print("Седловой точки НЕТ, игра решается в смешанных стратегиях.\n")


# 4. РАСЧЕТ ВЫИГРЫШЕЙ В СМЕШАННЫХ СТРАТЕГИЯХ

print("--- 2. Расчет выигрышей в смешанных стратегиях ---")

# H(P,Q) - средний выигрыш А, когда оба играют P и Q
# Формула: H(P,Q) = P * matrix * Q
# @ - это оператор матричного умножения в numpy
# Сначала P умножается на matrix, а результат - на Q
H_PQ = p_vec @ matrix @ q_vec

print(f"Средний выигрыш Игрока A в ситуации H(P,Q) = {H_PQ:.3f}")

# H(P, B_j) - средний выигрыш A, когда A играет P, а B играет чистую B_j
# Формула: H(P,B) = P * matrix
# Это даст нам сразу массив [H(P,B1), H(P,B2), ...]
H_PB_all = p_vec @ matrix

for j in range(len(H_PB_all)):
    print(f"Выигрыш Игрока A в ситуации H(P, B{j+1}) = {H_PB_all[j]:.3f}")


# 5. АКТИВНЫЕ СТРАТЕГИИ

print("\n--- 3. Активные стратегии ---")

# Ищем стратегии, где вероятность > 0
active_A = [f"A{i+1}" for i in range(len(P)) if P[i] > 0.001]
active_B = [f"B{i+1}" for i in range(len(Q)) if Q[i] > 0.001]

print(f"Активные стратегии Игрока A (P > 0): {active_A}")
print(f"Активные стратегии Игрока B (Q > 0): {active_B}")


# 6. ИТОГ

print("\n--- 4. Итог ---")
print(f"Цена игры (в смешанных стратегиях): {H_PQ:.3f}")
print(f"Оптимальная стратегия P: {P}")
print(f"Оптимальная стратегия Q: {Q}")

Дано:
Платежная матрица:
[[ 4  0  3  8 11]
 [ 6  9  1  4  3]
 [ 2  3  4  3  7]
 [ 2 11  5  0  4]
 [11  5  7  3  1]]

Смешанная стратегия P (Игрок А): [0.4  0.1  0.   0.01 0.4 ]
Смешанная стратегия Q (Игрок B): [0.2 0.2 0.2 0.4 0. ]

--- 1. Поиск седловой точки ---
Нижняя цена игры (α) = 2
Верхняя цена игры (β) = 7
Седловой точки НЕТ, игра решается в смешанных стратегиях.

--- 2. Расчет выигрышей в смешанных стратегиях ---
Средний выигрыш Игрока A в ситуации H(P,Q) = 4.676
Выигрыш Игрока A в ситуации H(P, B1) = 6.620
Выигрыш Игрока A в ситуации H(P, B2) = 3.010
Выигрыш Игрока A в ситуации H(P, B3) = 4.150
Выигрыш Игрока A в ситуации H(P, B4) = 4.800
Выигрыш Игрока A в ситуации H(P, B5) = 5.140

--- 3. Активные стратегии ---
Активные стратегии Игрока A (P > 0): ['A1', 'A2', 'A4', 'A5']
Активные стратегии Игрока B (Q > 0): ['B1', 'B2', 'B3', 'B4']

--- 4. Итог ---
Цена игры (в смешанных стратегиях): 4.676
Оптимальная стратегия P: [0.4, 0.1, 0.0, 0.01, 0.4]
Оптимальная стратегия Q: [0.2, 0